name: Doc

on:
  push:
    branches:
      - master

jobs:
  generate-document:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Generate document
        run: ./gradlew dokkaHtml

      - name: Commit files
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
          COMMIT_MSG: |
            Generate dokka document
            skip-checks: true

        run: |
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout master
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "${COMMIT_MSG}"; git push origin master)
